language: perl
perl:
- "5.18"
- "5.16"
- "5.14"
- "5.12"
- "5.10"

install:
- git clone --depth=50 --branch=master git://github.com/ingydotnet/testml-pm ../testml-pm
- cpanm --quiet --notest Devel::Cover::Report::Coveralls
- cpanm --quiet --notest --installdeps .

script:
- PERL5OPT=-MDevel::Cover=-coverage,statement,branch,condition,path,subroutine PERL5LIB=../testml-pm/lib prove -lv t/
- cover

after_success:
- cover -report coveralls
